/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package vit.devops.macse639.Assessment02;

/**
 *
 * @author darsh
 */
import java.time.LocalDateTime;
public class Report extends CEO {
    public Report(String login, String password) {
        super(login, password);
    }

    public void generateReport() {
        System.out.println("Report generated by 25MCS0064 at "
                + LocalDateTime.now());
    }
}
